{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "proxmox-k8s-sync.fullname" . }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "proxmox-k8s-sync.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "proxmox-k8s-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
