{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "proxmox-k8s-sync.fullname" . }}
rules:
  - verbs:
      - "get"
      - "list"
      - "watch"
    resources:
      - "nodes"
    apiGroups:
      - ""
{{- end }}
